### ISSUE TITLE
Code signature required in macOS 10.15 Catalina 

### ISSUE THREAD

**Issue by HRG1** [asmagill/hs._asm.axuielement#16]
This is the error message in Hammerspoon Console:

ERROR: error loading module 'hs._asm.axuielement.internal' from file '/Users/foo/.hammerspoon/hs/_asm/axuielement/internal.so':
	dlopen(/Users/foo/.hammerspoon/hs/_asm/axuielement/internal.so, 6): no suitable image found.  Did find:
	/Users/foo/.hammerspoon/hs/_asm/axuielement/internal.so: code signature in (/Users/foo/.hammerspoon/hs/_asm/axuielement/internal.so) not valid for use in process using Library Validation: library load disallowed by system policy

**Comment by latenitefilms** [comment]
Catalina requires everything to be code signed and notarised, so you'll have to sign this extension yourself.

**Comment by asmagill** [comment]
Hmm... haven't run this on Catalina yet (my development machine is still Mojave and I haven't installed Hammerspoon on my Catalina desktop yet).

Do *all* third party modules have to be individually signed as well now?

**Comment by latenitefilms** [comment]
Yes, I believe so.

**Comment by asmagill** [comment]
I've not needed to code sign this module (or any other I've installed externally) so I'm going to assume that this issue has been addressed by changes @cmsj made a while back to the developer build setting within XCode.

Re-open if you still have this issue or think I've missed something.
