### ISSUE TITLE
How do you call parameterized setter functions?

### ISSUE THREAD

**Issue by dbalatero** [asmagill/hs._asm.axuielement#18]
Hi @asmagill,

I have been reading the source of this library to try to understand it, but I'm at the limit of my understanding and I'm hoping to maybe clear up confusion (and maybe we can make a documentation patch as a result?).

When I explore the `dynamicMethods` of a `UITextField`, there is a method in the table `replaceRangeWithTextWithParameter` which I'd like to use to replace some text in the field.

I think it must correspond to this Objective-C method here: https://developer.apple.com/documentation/uikit/uitextinput/1614558-replacerange

However, it's unclear how to call it. My first guess was:

```lua
local range = {
  location = 10,
  length = 5
}

element:replaceRangeWithTextWithParameter(range, "12345")
```

which gave me:

```
2019-11-03 19:05:34: 19:05:34 ERROR:   LuaSkin: hs.hotkey callback: /Users/dbalatero/.hammerspoon/hs/_asm/axuielement/init.lua:272: ERROR: incorrect number of arguments. Expected 3, got 4
stack traceback:
	[C]: in field 'parameterizedAttributeValue'
	/Users/dbalatero/.hammerspoon/hs/_asm/axuielement/init.lua:272: in method 'replaceRangeWithTextWithParameter'
```

It seems to want a single argument passed in, so I tried:

```lua
element:replaceRangeWithTextWithParameter({
  range = {
    location = 10,
    length = 5
  },
  text = "12345"
})
```

I also tried:

```lua
element:replaceRangeWithTextWithParameter({
  {
    location = 50,
    length = 5
  },
  text = "12345"
})
```

I think there's some magic I'm missing here, and I'm hoping it might be a 1 minute obvious thing to you?

If you need a field to reproduce this in, the Hammerspoon console's REPL field is great and has the accessibility stuff turned on:

![image](https://user-images.githubusercontent.com/59429/68097690-51df7480-fe6d-11e9-990b-8dde100247c4.png)

**Comment by dbalatero** [comment]
@asmagill Also if there is just missing functionality here (I note some comments laying around about needing more work for parameterized values) let's chat and I can maybe try to figure out how to add it?

**Comment by latenitefilms** [comment]
Can you can an example of this kind of UI element in a build-in macOS application, so that I can try and reproduce?

If I have a look at an `AXTextField` (in my case the subject text field in Apple Mail), I can see a `AXReplaceRangeWithText` attribute, but it offers no controls in [UI Browser](https://pfiddlesoft.com/uibrowser/), so I can't do anything with it.

As a workaround, why not just get the `AXValue`, then manipulate in Lua-land, and send back?

**Comment by dbalatero** [comment]
@latenitefilms Hey, funny I just grepped your CommandPost project to see if you had already figured out how to do it, but didn't find anything :)

> Can you can an example of this kind of UI element in a build-in macOS application, so that I can try and reproduce?

Yes, the Search box in Finder will do:

![image](https://user-images.githubusercontent.com/59429/68099195-e4841180-fe75-11e9-8db0-121a679b1d15.png)

> If I have a look at an AXTextField (in my case the subject text field in Apple Mail), I can see a AXReplaceRangeWithText attribute, but it offers no controls in UI Browser, so I can't do anything with it.

I use this code snippet to get info out of the field. I focus the UI field, then hit `hyper + a`. If I go to the Hammerspoon console I can see the output

```lua
local inspect = hs.inspect.inspect

function outputFieldInfo()
  local systemElement = ax.systemWideElement()
  local currentElement = systemElement:attributeValue("AXFocusedUIElement")
  local role = currentElement:attributeValue("AXRole")

  if role == "AXTextField" or role == "AXTextArea" then
    logger.i("Currently in text field")
    logger.i(inspect(currentElement:parameterizedAttributeNames()))
    logger.i("attributes:")
    logger.i(inspect(currentElement:attributeNames()))
    logger.i("action names:")
    logger.i(inspect(currentElement:actionNames()))
    logger.i("dynamic methods:")
    logger.i(inspect(currentElement:dynamicMethods(true)))
    logger.i("range:")
    logger.i(inspect(currentElement:selectedTextRange()))
    logger.i("Position: ", inspect(currentElement:position()))
    logger.i("Selected text: ", inspect(currentElement:selectedText()))

    local lineNum = currentElement:insertionPointLineNumber()
    logger.i("Insertion point line: ", lineNum)
    local lineRange = currentElement:rangeForLineWithParameter(lineNum)
    logger.i("Insertion point content: ", inspect(lineRange))

    local text = currentElement:attributeValue("AXValue")
    local textLength = currentElement:attributeValue("AXNumberOfCharacters")
    local range = currentElement:attributeValue("AXSelectedTextRange")

    logger.i("range = " .. inspect(range))
    logger.i("len = " .. textLength)
    logger.i("Text is " .. text)
  else
    logger.i("Role = " .. role)
  end
end

-- choose your binding
hs.hotkey.bind(hyper, 'a', outputFieldInfo)
```

You can just look at the `dynamicMethods` output to see the `replaceRangeWithTextWithParameter ` method I'm talking about.

> As a workaround, why not just get the AXValue, then manipulate in Lua-land, and send back?

Yep I already have that code working. It's pushing up against me perceiving a small enough UX delay when I fire it, so I was hoping that using built-in replacement methods on OS X could do a faster in-memory replace. If I can't get this working I will fallback to it…

**Comment by latenitefilms** [comment]
I don't think this is a `hs._asm.axuielement` issue - I have a feeling `AXReplaceRangeWithText` is depreciated or a work-in-progress tool (it was added in Mojave), as you can't even see it in Xcode's Accessibility Inspector. As explained, I also tried UI Browser, but it didn't work there either.

Seems we're not alone: https://stackoverflow.com/questions/52698757/what-is-the-axreplacerangewithtext-macos-accessibility-attribute

**Comment by dbalatero** [comment]
> I don't think this is a hs._asm.axuielement issue - I have a feeling AXReplaceRangeWithText is depreciated or a work-in-progress tool (it was added in Mojave), as you can't even see it in Xcode's Accessibility Inspector. As explained, I also tried UI Browser, but it didn't work there either.

Hah well there you go! I'll stop barking up this tree then.

**Comment by qbhamsandwhich** [comment]
@dbalatero  Were you able to figure out how to use this?

**Comment by dbalatero** [comment]
@qbhamsandwhich no, why?

**Comment by qbhamsandwhich** [comment]
I am trying to come up with a way to replace selected text in Chromium-based apps using accessibility.
