### ISSUE TITLE
asHSWindow() Crashes

### ISSUE THREAD

**Issue by latenitefilms** [asmagill/hs._asm.axuielement#4]
FYI: I can fairly consistently get Hammerspoon to crash with the following code:

```
local elementUnderMouse = ax.systemElementAtPosition(mouse.getAbsolutePosition())
if elementUnderMouse ~= nil then print(elementUnderMouse:asHSWindow()) end
```

I'm assuming you already have all my crash logs!

**Comment by asmagill** [comment]
The AXRef was getting released twice during garbage collection... the hs.window code I had linked to doesn't do an explicit retain and I had missed this in my initial tests.  The latest update should fix it for you.

**Comment by latenitefilms** [comment]
Legend, thank you! Will test out!
