### ISSUE TITLE
Possible leak in pushAXUIElement()?

### ISSUE THREAD

**Issue by cmsj** [asmagill/hs._asm.axuielement#8]
Hey @asmagill 

I was just chatting with @latenitefilms about `axuielement` and he asked me to take a look at `getApplicationElementForPID()` as a possible source of leaks. I suspect that the Leaks profile in Instruments.app is being overzealous, but I did notice that `pushAXUIElement()` has a `CFRetain()` call in it.

By my reckoning, `AXUIElementCreateApplication()` on line 165 is returning a pointer that has a refcount of +1, so `pushAXUIElement()` is pushing that to +2. That would mean that the `__gc` metamethod is only popping the refcount back to +1 and the memory will never be freed.

Did I misunderstand something?

**Comment by cmsj** [comment]
Derp, I misread the codepath in `getApplicationElementForPID()`, there is a `CFRelease()` there which balances out the refcount (although it's theoretically possible that if `isApplicationOrSystem()` returns false, there could be a leak).

**Comment by latenitefilms** [comment]
@cmsj - Actually, I think you were right on the money:

<img width="1388" alt="screen shot 2018-07-10 at 8 55 31 pm" src="https://user-images.githubusercontent.com/22286696/42505945-bf15226c-8483-11e8-9174-6854d32dc5ce.png">

Thoughts @asmagill ?

**Comment by latenitefilms** [comment]
Simple fix?

```
static int getApplicationElementForPID(lua_State *L) {
    LuaSkin *skin = [LuaSkin shared] ;
    [skin checkArgs:LS_TNUMBER, LS_TBREAK] ;
    pid_t thePid = (pid_t)luaL_checkinteger(L, 1) ;
    AXUIElementRef value = AXUIElementCreateApplication(thePid) ;
    if (value && isApplicationOrSystem(value)) {
        pushAXUIElement(L, value) ;

    } else {
        lua_pushnil(L) ;
    }
    if (value) {
	    CFRelease(value) ;
    }
    return 1 ;
}
```

**Comment by latenitefilms** [comment]
Looks like it worked! Now we just need to solve this leak in `hs._asm.cfpreferences`!

<img width="1396" alt="screen shot 2018-07-10 at 9 04 41 pm" src="https://user-images.githubusercontent.com/22286696/42506334-eb04226e-8484-11e8-870c-0e058b4f6c14.png">

**Comment by cmsj** [comment]
@latenitefilms yeah I would say your fix there looks good

**Comment by latenitefilms** [comment]
@cmsj - Unrelated to this issue, but just while I've got you - here's some other leaks I'm seeing:

<img width="1689" alt="screen shot 2018-07-11 at 12 01 42 am" src="https://user-images.githubusercontent.com/22286696/42514818-a49f08b6-849d-11e8-9c44-90b1cfbf3a13.png">

**Comment by asmagill** [comment]
lgtm, not sure how I missed that. If you want to do a pull request at https://github.com/asmagill/hs._asm.axuielement I'll merge it, or I'll try and fix it myself later this week.

**Comment by latenitefilms** [comment]
@asmagill - Legend, thanks mate! I've just added a pull request.
